version: '3.8'
services:
  web-app:
    restart: always
    build: ..
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      - SHIORI_DBMS=postgresql
      - SHIORI_PG_USER=postgres
      - SHIORI_PG_PASS=postgres
      - SHIORI_PG_NAME=shiori_db
      - SHIORI_PG_HOST=db
      - SHIORI_PG_PORT=5432
    volumes:
      - shiori:/shiori  
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shiori_db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
  shiori:
    driver: local  